services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit max_message_size 209715200"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  data_loader:
    build: data_loader./
    depends_on:
      - plotter
    networks:
      - rabbit

  data_analyzer:
    build: data_analyzer/.
    # container_name: data_analyzer
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbit
  plotter:
    build: plotter/.
    container_name: plotter
    depends_on:
      - data_analyzer
    networks:
      - rabbit
    volumes:
      - ./plot:/output

networks:
  rabbit:
    driver: overlay
    attachable: true

